#Independent settings for the local costmap
local_costmap:
    publish_voxel_map: false
    global_frame: map
    robot_base_frame: base_footprint
    update_frequency: 0.5
    publish_frequency: 0.5
    static_map: false
    rolling_window: true
    width: 5.0
    height: 5.0
    resolution: 0.05
    origin_x: 0.0
    origin_y: 0.0

    plugins:
     - {name: static_layer,        type: "costmap_2d::StaticLayer"}
     - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
     - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}

